# Generated by Django 3.2.6 on 2021-08-27 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.poll', verbose_name='Опрос вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, help_text='дата старта, после сохранения не редактируется', verbose_name='Дата старта'),
        ),
    ]
