# Generated by Django 3.2.6 on 2021-08-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210827_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionitem',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_items', to='polls.question', verbose_name='Вариант ответа на вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='polls.poll', verbose_name='Опрос вопроса'),
        ),
    ]
