# Generated by Django 3.2.6 on 2021-08-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210827_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_as_text',
            field=models.TextField(help_text='По ТЗ ответ может быть простым текстом', max_length=1024, null=True, verbose_name='Ответ как текст'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_item',
            field=models.ForeignKey(help_text='Выбранный вариант ответа', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.questionitem', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='pollsession',
            name='session_id',
            field=models.IntegerField(help_text='Чтобы не хреначить кучу сессий опросов', null=True, verbose_name='Сессия для сессии опроса, если аноним'),
        ),
        migrations.AlterField(
            model_name='pollsession',
            name='user_id',
            field=models.IntegerField(help_text='в ТЗ указано так,             будто пользователь может приходить из левой системы            , поэтому числовой ID, а не FK на base_auth_model', null=True, verbose_name='Числовой идентификатор пользователя сессии опроса'),
        ),
    ]
