# Generated by Django 3.2.6 on 2021-08-29 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210827_2240'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
                ('answers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('questions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='questionitem',
            managers=[
                ('question_items', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='poll_session',
            field=models.ForeignKey(help_text='Сессия, в которой был дан ответ на вопрос', on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='polls.pollsession', verbose_name='Сессия опроса'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Вопрос, на который был дан ответ', on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='polls.question', verbose_name='Вопрос'),
        ),
    ]
